### ISSUE TITLE
How is Tango data record?

### ISSUE THREAD

**Issue by pangfumin** [daniilidis-group/penncosyvio#1]
Hi,
Thank you for sharing your dataset, it a good dataset to evaluate vio algrithem.
Because I am very new to android develop, can you give more detail on how the Tango data is record?
I know the Tango API can get fisheye data(I think),how is raw imu data is record?
I will　apprecisate it if you can give more information?
Thanks in advence.

**Comment by pangfumin** [comment]
Hi,
Thank you for sharing your dataset, it a good dataset to evaluate vio algrithem.
Because I am very new to android develop,  can you give more detail on how the Tango data is record?
I know the Tango API can get fisheye data(I think),how is raw imu data is record?
I will　apprecisate it if you can give more information?
Thanks in advence.

**Comment by berndpfrommer** [comment]
Sorry for the late reply (on vacation)!

We got the IMU data through the Android (not Tango) API. Here is the link
to the relevant docs:

https://developer.android.com/guide/topics/sensors/sensors_motion.html

Regards,

Bernd
