### ISSUE TITLE
Rolling shutter readout times

### ISSUE THREAD

**Issue by hovren** [daniilidis-group/penncosyvio#3]
Rolling shutter-aware algorithms usually require that you know the rolling shutter readout time of the camera. However, I can not find this anywhere in the dataset.
Did I miss it? If not, could this be added to the dataset?

**Comment by berndpfrommer** [comment]
Sorry, but I could not find rolling shutter readout times provided by the manufacturer. For our purposes we did not correct for rolling shutter effects.

The following website claims 30ms readout time, but I don't know where they get the data from, and if it is applicable to our dataset.

https://pix4d.com/rolling-shutter-correction/
