### ISSUE TITLE
incorrect frame count with ffmpeg

### ISSUE THREAD

**Issue by guohengkai** [daniilidis-group/penncosyvio#4]
Hi,

When I use the extract_frames.bash with ffmpeg, the frame counts for all sequences of tango bottom are wrong. For example, the duration of "as" is 02:36.27 (4689 frames) while the extracted frame count is 4666.

**Comment by guohengkai** [comment]
This is only happened on Mac. So close this issue.

**Comment by berndpfrommer** [comment]
Thanks for documenting this "feature" :)
