### ISSUE TITLE
A few question

### ISSUE THREAD

**Issue by mpkuse** [daniilidis-group/penncosyvio#5]
Hi,
Thanks for creating this dataset with ground truth. 

I have the following 2 questions. I have downloaded all your data. 
a) What is af, as, bf, bs. Is there any significance of this. I got a bit comfused.

b) is there a utility to convert this to rosbag?

**Comment by berndpfrommer** [comment]
Really, sorry, just saw this one right now. No idea how I missed it!

AS: sequence A, slow
AF: sequence A, fast
BS: sequence B, slow
BF: sequence B, fast

Here are some pointers for pulling video from a rosbag:
https://answers.ros.org/question/44777/how-to-extract-video-from-bag-file/ 
https://github.com/mlaiacker/rosbag2video
