### ISSUE TITLE
About the IMU innertial parameter

### ISSUE THREAD

**Issue by JKTao** [daniilidis-group/penncosyvio#6]
I failed to find the innertial parameter of IMU such as cov_bg, cov_ba on your website.
Could you please provide it for me? Thanks you......

**Comment by berndpfrommer** [comment]
Alas, Google did not disclose what IMU they built into the yellowstone tablet, and we did not measure the IMU noise parameters ourselves.

I recommend having a look here

https://github.com/rpng/kalibr_allan

At the bottom there are some graphs for the yellowstone tablet.
You may want to try those parameter and see if they work for you.
