### ISSUE TITLE
the number of frames does not agree with number of files

### ISSUE THREAD

**Issue by HarborC** [daniilidis-group/penncosyvio#8]
![image](https://github.com/daniilidis-group/penncosyvio/assets/28862505/cbd4babe-49cc-4fec-9d73-02d11e92b3af)

Thanks for your good work! In ubuntu 20.04, I use ffmpeg to extract mp4 file, and I find this mistack, can you help me for this question!

**Comment by HarborC** [comment]
I try to extract C1 gopro data.

**Comment by ilknurbas** [comment]
Hi, I am encountering the same issue, how did you fix it?
